config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get '/about', to: 'pages#about'
  
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :articles  do
    resources :comments
  end
  
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
  
  resources :conversations do
    resources :messages
  end

 

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  has_many :comments, dependent: :destroy
  
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :city, presence: true, length: { minimum: 2, maximum: 50 }
  validates :country, presence: true, length: { minimum: 2, maximum: 50 }
  validates :description, presence: true, length: { minimum: 30 }
  validates :user_id, presence: true
  
  default_scope { order(created_at: :desc) }
  
  def comment_count
    self.comments.count
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @article = Article.new
  end
  
  def show
    @comments = @article.comments.paginate(page: params[:page], per_page: 3)
    @comment = @article.comments.new
  end
  
  def edit
  end
  
  def update
     if @article.update(article_params)
       flash[:success] = "Your article was updated successfully!"
       redirect_to article_path(@article)
     else
       render 'edit'
     end
  end
  
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Your article was created successfully!"
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end 
  
  def destroy
    @article.destroy
    flash[:danger] = "Your story was deleted succesfully."
    redirect_to articles_path
  end
  
  private
  
    def article_params
      params.require(:article).permit(:title, :city, :country, :description, category_ids: [])
    end
    
    def set_article
      @article = Article.find(params[:id])
    end
    
    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles."
        redirect_to root_path
      end
      
    end
    
    
    
end 

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <div class="well well-lg">
        
        <h3><div class="article-title center">
          <%= link_to article.title, article_path(article) %>
        </div>
        </h3>

        </br>
        
        <div class="article-body">
          <strong>Written by: </strong><%= article.user.username if article.user %>
        </div>
        
        <div class="article-body">
          <strong>I visited: </strong><%= article.city %>, <%= article.country %>
        </div>
        
        <!--Categories  -->
          <% if article.categories.any? %>
          <p><strong>Categories: </strong> <%= render article.categories %>
          <% end %> </p>
         <!--End Categories  -->
        
        <div class="article-body">
          <strong>My story: </strong><%= truncate(article.description, length: 200) %>
        </div>
        
        
        <!--Action Buttons-->
        <div class="index actions">
          <div><small>
              Written: <%= time_ago_in_words(article.created_at) %> ago, 
              last updated: <%= time_ago_in_words(article.updated_at) %> ago.</small>
          </div>
          

          
          <% if logged_in? && (current_user == article.user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-warning" %> |
            <%= link_to "Delete", article_path(article), method: :delete, 
                                                data: { confirm: "Are you sure you want to delete this article?" }, 
                                                class: "btn btn-xs btn-danger" %>
          <% end %>
          
        </div>
        

      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-md-12">
    
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    
      <!--title-->
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title, "Story Title" %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "", autofocus: true %>
        </div>
      </div>
      
      <!--city-->
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :city, "City" %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :city, class: "form-control", placeholder: "", autofocus: true %>
        </div>
      </div>
      
      <!--country-->
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :country, "Country" %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :country, class: "form-control", placeholder: "", autofocus: true %>
        </div>
      </div>
      
      <!--description-->
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description, "Your Story" %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "", autofocus: true %>
        </div>
      </div>
      
      <!--Categories-->
      <div class="form-group text-center">
        <div class="row">
          <div class="col-sm-8 col-sm-offset-2">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
            <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>
      
      <!--submit button-->
      <div class="form-group text-center">
        <div class="col-sm-8 col-sm-offset-2">
          <%= f.submit class: 'btn btn-success btn-lg' %>
        </div>
      </div>
      
    <% end %>
    <!--<div class="col-xs-4 col-xs-offset-4">-->
    <!--  <%= link_to "Cancel Submission and Return to All Stories", articles_path %>-->
    <!--</div>-->
  </div>
</div>

app/views/articles/edit.html.erb
<h1> Edit your Story </h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<body class ="image responsive index-bg">
  <h1 class="text-center">All Stories</h1>
    <div align="center">
      <%= will_paginate %>
    </div>
    <%= render 'article', obj: @articles %>
    <div align="center">
      <%= will_paginate %>
    </div>
</body>

app/views/articles/new.html.erb
<h1 class="center"> Create a Story </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center"><%= @article.title %></h2>
</br>
<div class="well col-xs-10 col-xs-offset-1">
  <% if @article.user %>
    <ul class="listing">
      <div class="row center">
        <div class="col-md-12 ">
          
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
          <li class="article-title">
            <%= link_to @article.user.username, user_path(@article.user) %>
          </li>
          <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
          </small></li>
          
        </div>
      </div>
    </ul>
  <% end %>
    
  <p><strong>Country:</strong> <%= @article.country %></p>

  <p><strong>City:</strong> <%= @article.city %></p>
  
<!--Category -->
  <% if @article.categories.any? %>
    <p><strong>Category:  </strong> <%= render @article.categories %></p>
  <% end %>
<!--End Category-->
  
  <hr>
  <p><strong>My Story:</strong> </br> </br> 
  <%= @article.description %></p>

  <div class="article-actions text-center">
    <%= link_to "Back to All Stories", articles_path, class: "btn btn-xs btn-primary" %>  
    
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>| 
      <%= link_to "Edit this Story", edit_article_path(@article), class: "btn btn-xs btn-warning" %> |
      <%= link_to "Delete this Story", article_path(@article), method: :delete, 
                                          data: { confirm: "Are you sure you want to delete this story?" }, 
                                          class: "btn btn-xs btn-danger" %>
    <% end %>
  </div>
</div>



<!-- Comments section -->

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <% if @comments.any? %>
      <div class="row">
        <div class="col-md-12">
          <h4 class="text-center bold"><%= pluralize(@article.comment_count, 'comment') %>:</h4>
          <%= will_paginate @comments %>
        </div>
      </div>
    <% end %>
    
    <% if @comments.any? %>
      <% @comments.each do |comment| %>
        <hr>
        <div class="row">
          <div class="col-md-2 offset-1">
            <section class="user_info comment_img center">
              <%= link_to gravatar_for(comment.user, size: 70), user_path(comment.user) %>
            </section>
          </div>
          <div class="col-md-9">
             <p class="inline-text">
               <span class="quiet"><small><strong><%= link_to comment.user.username, user_path(comment.user) %></strong>  <%= time_ago_in_words(comment.created_at) %> ago  </small></span>
             </p>
            <span class="quiet"><%= comment.body %></span>
            
            
          </div>
        </div>
       <% end %>
       <hr>
    <% end %>
  </div>
</div>

<% if logged_in? %>
  <div class="row">
    <div class="col-md-8  col-md-offset-2">
      <h3 class="text-center">Leave a comment</h3>
      
        <%= form_for([@article,@comment]) do |f| %>
          <!-- Error section -->
          <% if @comment.errors.any? %>
            <div class="row">
              <div class="alert alert-danger col-md-8 col-md-offset-2">
                <h5>Please correct the following error(s):</h5>
                <ul>
                  <% @comment.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          <% end %>
          <!-- Error ends -->
        <div class="well">

          <div class="control-group">
        
            <%= f.text_area :body, class: "col-md-12 comment-text", rows: "7", placeholder: "Say something nice!" %>
        
          <div class="text-center">
            <%= f.submit 'Post Comment', class: "btn btn-success btn-md text-center" %>
          </div>
        <% end %>
        
      </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-12 comment-footer text-center">
      <p>Please <%= link_to "Log in", login_path %> or <%= link_to "Sign up", signup_path %> to leave your comment.</p>
    </div>
  </div>
<% end %>