config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get '/about', to: 'pages#about'
  
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :articles  do
    resources :comments
  end
  
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
  
  resources :conversations do
    resources :messages
  end

 

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  
  def index
    @categories = Category.order('name ASC').paginate(page: params[:page], per_page: 7)
  end

  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "The category was created successfully!"
      redirect_to categories_path
    else
      render 'new'
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "The category name was updated successfully."
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end
  
  
  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end
  
  private
  def category_params
    params.require(:category).permit(:name)
  end
  
  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = "Only admins can perform this action."
      redirect_to categories_path
    end
    
  end
  
end

app/views/categories/_category.html.erb
<span class="badge text-center">
  <%= link_to category.name, category_path(category) %>
</span>
 

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

</br>
</br>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>

  <!--username-->
  <div class="form-group">
    <div class="control-label col-sm-3">
      <%= f.label :name, "Category: " %>
    </div>
    
    <div class="col-sm-6">
      <%= f.text_field :name, class: "form-control", placeholder: "For instance: Backpacking, City Trip, Study Abroad...", autofocus: true %>
    </div>
  </div>
  
  </br>
  </br>

  <!--submit button-->
  <div class="form-group text-center">
    <div class="col-sm-8 col-sm-offset-2">
      <%= f.submit class: 'btn btn-success btn-lg' %>
    </div>
  </div>
  
<% end %>
    
    <!--<div class="col-xs-4 col-xs-offset-4">-->
    <!--  <%= link_to "Return to Home", root_path %>-->
    <!--</div>-->
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="center"> Edit this Category </h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="center"> All Categories </h1>
</br>
</br>
<div class="text-center">
  <%= will_paginate %>
    <% @categories.each do |category| %>
    
      <ul class="listing">
        <div class="row center">
          <div class="well col-md-4 col-md-offset-4">
            <li class="article-title">
             
              <strong><%= link_to "#{category.name}", category_path(category) %></strong>
            </li>
              </br>
              
            <li><small><%= pluralize(category.articles.count, "article") %> </small></li>
            <% if logged_in? and current_user.admin? %>
            </br>
              <%= link_to "Edit", edit_category_path(category), class: "btn btn-xs btn-warning" %> 
            <% end %>
          </div>
         
        </div>
        
      </ul>
    <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 class="center"> Create a New Category </h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<body class ="image responsive index-bg">
  <h1 class="text-center"><%= "All " + @category.name + " Stories" %> </h1>
    <div align="center">
      
      
    
 
      
      
      
      
      <%= will_paginate @category_articles %>
    </div>
    <%= render 'articles/article', obj: @category_articles %>
    <div align="center">
      <%= will_paginate @category_articles %>
    </div>
</body>