config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get '/about', to: 'pages#about'
  
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :articles  do
    resources :comments
  end
  
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
  
  resources :conversations do
    resources :messages
  end

 

end

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="footer"> 
    <p>Created by Sandra Adams-Hallie &copy;2016. All rights reserved. </p>
  </div>
</div>

app/views/layouts/_lookup.html.erb
<!-- When submit the form, the view rendered will be the index view of our articles resource -->
<%= form_tag(articles_path, :method => "get", class: "navbar-form", id: "search-form") do %>
  <div class="input-append">
    <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Articles" %>
    <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
         of using a Rails form helper -->
    <button class="btn" type="submit"><i class="icon-search"></i></button>
  </div>

app/views/layouts/_messages.html.erb
<div class="row text-center">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Globetrotter", root_path, class:"navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
          <li><%= link_to "All Stories", articles_path %></li>
          <li><%= link_to "All Users", users_path %></li>
          <li><%= link_to "Travel Categories", categories_path %></li>
        
          
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %><%= " | Admin" if current_user.admin? %> <span class="caret"></span></a>
            <ul class="dropdown-menu">

              <li><li><%= link_to "New Story", new_article_path %></li></li>
              
              <% if current_user.admin? %>
              <li><%= link_to 'New Category', new_category_path %></li>
              <% end %>
              
              <li><li><%= link_to "View my Profile", user_path(current_user) %></li></li>
              <li><li><%= link_to "Settings", edit_user_path(current_user) %></li></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Logout', logout_path, method: :delete %> </li>
            </ul>
          </li>
          
        <% else %>
        
          <li><%= link_to 'Login', login_path %> </li>
          <li><%= link_to 'Signup', signup_path %> </li>
          
        <% end %>
        
      </ul>
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>Globetrotter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <meta content='<%= logged_in? ? current_user.id : "" %>' name='user-id'/>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
</head>
<body>
  <%= render 'layouts/navigation' %>
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <!--<%= debug(params) if Rails.env.development? %>-->

</body>
</html>